FROM python:3.11-slim

WORKDIR /app

COPY ../requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY ../app/ .

ENV OPENAI_API_KEY=${OPENAI_API_KEY}

CMD ["python", "llm_sql_assistant.py"]